---
- name: Cleanup
  user: ansible
  hosts: all
  become: yes
  vars:
    - runner_user: ansible
    - github_repo: ansible-github_actions_runner-testrepo
    - github_account: monolithprojects
  tasks:
    - include_role:
        name: ansible-github_actions_runner
        apply:
          tags:
            - uninstall 