---
- name: Dev test playbook
  user: ansible
  hosts: all
  gather_facts: yes
  become: yes
  vars:
    runner_user: ansible
    github_repo: "{{ lookup('env', 'GITHUB_REPO') }}"
    github_account: "{{ lookup('env', 'GITHUB_ACCOUNT') }}"
    runner_version: "latest"
    runner_name: test_name
    runner_on_ghes: yes
    reinstall_runner: false
    hide_sensitive_logs: no
    runner_labels:
        - label1
        - repo-runner
  roles:
    - robertdebock.epel
    - monolithprojects.github_actions_runner
