---
driver:
  name: docker
lint: |
  yamllint .
platforms:
  - name: CentOS7
    image: monolithprojects/systemd-centos7:latest
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: no
    pre_build_image: yes
  - name: CentOS8
    image: monolithprojects/systemd-centos8:latest
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: no
    pre_build_image: yes
  # - name: Ubuntu16
  #   image: monolithprojects/systemd-ubuntu16:latest
  #   command: /sbin/init
  #   tmpfs:
  #     - /run
  #     - /tmp
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: no
  #   pre_build_image: yes
  # - name: Ubuntu18
  #   image: monolithprojects/systemd-ubuntu18:latest
  #   command: /sbin/init
  #   tmpfs:
  #     - /run
  #     - /tmp
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: no
  #   pre_build_image: yes
provisioner:
  name: ansible
  log: false
  env: 
    PERSONAL_ACCESS_TOKEN: $PERSONAL_ACCESS_TOKEN
  inventory:
    host_vars:
      CentOS8:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - cleanup
    - destroy