---
- name: Cleanup
  user: ansible
  hosts: all
  become: yes
  vars:
    runner_user: ansible
    github_account: monolithprojects-testorg
    runner_org: yes
    runner_state: absent
  roles:
    - monolithprojects.github_actions_runner
