---
- name: Install Org Runner
  user: ansible
  hosts: all
  become: yes
  vars:
    runner_user: ansible
    github_account: monolithprojects-testorg
    runner_org: yes
    runner_state: "stopped"
    runner_version: "2.303.0"
  roles:
    - robertdebock.epel
    - monolithprojects.github_actions_runner
