---
- name: Cleanup
  user: ansible
  hosts: all
  become: yes
  vars:
    - runner_user: ansible
    - github_repo: ansible-github_actions_runner-testrepo
    - github_account: monolithprojects
    - runner_state: absent
    - runner_org: yes
  roles:
    - ansible-github_actions_runner