---
- name: Converge
  user: ansible
  hosts: all
  become: yes
  vars:
    - runner_user: ansible
    - github_repo: ansible-github_actions_runner-testrepo
    - github_account: monolithprojects-testorg
    - runner_org: yes
  roles:
    - robertdebock.epel
    - ansible-github_actions_runner