---
- name: Install Repo runner
  user: ansible
  hosts: all
  gather_facts: yes
  become: yes
  vars:
    runner_user: ansible
    github_repo: ansible-github_actions_runner-testrepo
    github_account: monolithprojects-testorg
    runner_version: "latest"
    runner_labels:
        - label1
        - repo-runner
  roles:
    - robertdebock.epel
    - monolithprojects.github_actions_runner
