---
name: Release to Ansible Galaxy

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: galaxy
        uses: robertdebock/galaxy-action@1.0.1
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
          